name : Commits-msg

on :
  push :
    branches : [ "main"]

jobs :
  build :
    runs-on : ubuntu-latest

    steps :
      - name : Checkout code
        uses : actions/checkout@v4

      - name : Run simple command
        run : echo "Hello from github Actions Done ! "

# this is a comment
